# Generated by Django 4.1.3 on 2023-05-11 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(max_length=100, verbose_name='Brand name')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='Product group picture')),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='Feature name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product description')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='Product picture')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Product price')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active/Deactive')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('register_date', models.DateTimeField(auto_now=True, verbose_name='Register date')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.brand', verbose_name='Product brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='Product group title')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='Product group picture')),
                ('description', models.TextField(blank=True, verbose_name='Product group description')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active/Deactive')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('register_date', models.DateTimeField(auto_now=True, verbose_name='Register date')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='products.productgroup', verbose_name='Parent product group')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='Product group picture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Product feature value')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature', verbose_name='Feature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(through='products.ProductFeature', to='products.feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ManyToManyField(related_name='products_of_groups', to='products.productgroup', verbose_name='Product group'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product_group',
            field=models.ManyToManyField(related_name='feature_of_groups', to='products.productgroup', verbose_name='Product group'),
        ),
    ]
