# Generated by Django 4.1.3 on 2023-05-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Molbile Number'),
        ),
    ]
