# Generated by Django 4.1.3 on 2023-07-15 10:46

from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title 1')),
                ('slider_title_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title 2')),
                ('slider_title_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title 3')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='Slider Image')),
                ('slider_link', models.URLField(blank=True, null=True, verbose_name='Slider Link')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active/Inactive')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Register Date')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
        ),
    ]
